---
title: "Vis"
author: "ZG"
date: "2023-01-03"
output: html_document
---
```{r setup}
library(tidyverse)
library(readr)

library(ggplot2)
```

# 1.Importation des données
```{r}
data1 <- read.csv("../../A_Datas/df_tidy_for_db3.csv",encoding = 'UTF-8')
head(data1)
```
# Traitement des données

```{r}
data2 <- data1 %>% 
    filter(indicateur == 'patient_gender', p_n == 0) %>% 
    select(-c(p_n, indicateur))

AddRow=c(NA, 
         nrow(data2)+1, 
         data2[1,(ncol(data2)-1):ncol(data2)])
data2 <- rbind(data2, as.numeric(AddRow))

data2 <- data2 %>% 
  mutate(id = c(1:6))
data2  %>%
  ggplot(aes(x=id)) +
  geom_polygon(aes(y=standard),color = "black", fill= "#ffd200",alpha=0.1)+
  geom_point(aes(y=standard, fill= "#ffd200"),size=5,shape=21,color = 'black',fill= "#ffd200")+
  
  geom_polygon(aes(y=mean),color = "black", fill= "#304156",alpha=0.1)+
  geom_point(aes(y=mean, fill= "#304156"),size=5,shape=21,color = 'black', fill= "#304156")+
  
  geom_polygon(aes(y=median),color = "black", fill= "#f8766d",alpha=0.1)+
  geom_point(aes(y=median, fill= "#f8766d"),size=5,shape=21,color = 'black', fill= "#f8766d")+
  
  coord_polar() +
  scale_x_continuous(breaks = data2$id,labels=data2$name)+
  theme_light()+
  theme(axis.text.x=element_text(size = 8,colour="black"))+
    labs(
    title = " ",
    # subtitle = " ",
    caption = "Data source: Aymeric Stamm"  )
```
