---
title: "R Project : Dashboard 3"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(shiny)
library(readr)

data <- read.csv("../A_Datas/age_3.csv",encoding = 'UTF-8')


data1 <- read.csv("../A_Datas/thyroid_tidy.csv",encoding = 'UTF-8')

data2 <- read.csv("../A_Datas/df_tidy_for_db3.csv")
```


Input {.sidebar}
-----------------------------------------------------------


```{r}
type <- c("patient_gender", "presc_thyroxine", "queried_why_on_thyroxine", 
          #"presc_anthyroid_meds", 
          "sick", 
          #"pregnant", "thyroid_surgery", 
          "radioactive_iodine_therapyI131", "query_hypothyroid", "query_hyperthyroid", "lithium", "goitre", "tumor", "hypopituitarism", "psych_condition", "TSH_measured", "T3_measured", 
          # "T4_measured", 
          "thyrox_util_rate_T4U_measured", "FTI_measured")

selectInput('xcol', 'X Variable', colnames(data1)[25:29],
                selected=colnames(data1)[[25]])

selectInput('ycol', 'Y Variable', colnames(data1)[25:29],
                selected=colnames(data1)[[26]])

selectInput('var', 'Variable', c(colnames(data1)[2:24],colnames(data1)[30]),
                selected=colnames(data1)[[5]])

# Définir la barre latérale (onglets)
selectInput('data', 'data_name', type,
            selected=type[[1]])

selectInput("variable",  # 传入变量名称
            "gender：", # 提示文字
            list("male" = "0",
                 "female" = "1"))
    
# varSelectInput("variable", "Variable:", data)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Numerical variable comparison

```{r, fig.height=10}
data1_2 <- data1 %>% 
  filter(ThyroidClass == "sick")

renderPlot({
  ggplot(data = data1_2, 
         mapping = aes_string(x = input$xcol,
                       y = input$ycol,
                       color = input$var)) + 
  geom_point() +
    labs(
    x = as.character(input$xcol),
    y = as.character(input$ycol),
    # title = "Numerical variable comparison",
    subtitle = " ",
    caption = "Data source: Aymeric Stamm"  )
})
```


Column {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Male
```{r}
renderPlot({
  data2 <- data2 %>% 
    filter(p_n == input$variable, indicateur == input$data) %>% 
    select(-c(p_n, indicateur))

AddRow=c(NA, 
         nrow(data2)+1, 
         data2[1,(ncol(data2)-1):ncol(data2)])
data2 <- rbind(data2, as.numeric(AddRow))

data2 %>% 
  mutate(id = c(1:6)) %>% 
  ggplot(aes(x=id)) +
  geom_polygon(aes(y=standard),color = "black", fill= "#ffd200",alpha=0.1)+
  geom_point(aes(y=standard, fill= "#ffd200"),size=5,shape=21,color = 'black',fill= "#ffd200")+
  
  geom_polygon(aes(y=mean),color = "black", fill= "#304156",alpha=0.1)+
  geom_point(aes(y=mean, fill= "#304156"),size=5,shape=21,color = 'black', fill= "#304156")+
  
  geom_polygon(aes(y=median),color = "black", fill= "#f8766d",alpha=0.1)+
  geom_point(aes(y=median, fill= "#f8766d"),size=5,shape=21,color = 'black', fill= "#f8766d")+
  
  coord_polar() +
  # scale_x_continuous(breaks =data2$id,labels=data2$name)+
  theme_light()+
  theme(axis.text.x=element_text(size = 8,colour="black"))+
    labs(
    title = "Comparison of male indicators",
    subtitle = " ",
    caption = "Data source: Aymeric Stamm"  )
})
```

### Female

```{r, fig.height=10}
renderTable({
data4 <- data %>% 
  filter(patient_gender != input$variable) %>% # input$variable
  select(-(patient_gender)) %>% 
  mutate(id = c(1:6))})

renderPlot({
  ggplot(data=data4, aes(x=id)) +
  geom_polygon(aes(y=standard),color = "black", fill= "#ffd200",alpha=0.1)+
  geom_point(aes(y=standard, fill= "#ffd200"),size=5,shape=21,color = 'black',fill= "#ffd200")+
  
  geom_polygon(aes(y=mean),color = "black", fill= "#304156",alpha=0.1)+
  geom_point(aes(y=mean, fill= "#304156"),size=5,shape=21,color = 'black', fill= "#304156")+
  
  geom_polygon(aes(y=median),color = "black", fill= "#f8766d",alpha=0.1)+
  geom_point(aes(y=median, fill= "#f8766d"),size=5,shape=21,color = 'black', fill= "#f8766d")+
  
  coord_polar() +
  scale_x_continuous(breaks =data4$id,labels=data4$name)+
  theme_light()+
  theme(axis.text.x=element_text(size = 8,colour="black"))+
    labs(
    title = "Comparison of female indicators",
    subtitle = " ",
    caption = "Data source: Aymeric Stamm"  )
})
```


### Male
```{r}
renderTable({
data2 <- data2 %>% 
    filter(indicateur == 'patient_gender') %>% 
    filter(p_n == input$variable) %>% 
    select(-c(p_n, indicateur))

AddRow=c(NA, 
         nrow(data2)+1, 
         data2[1,(ncol(data2)-1):ncol(data2)])
data2 <- rbind(data2, as.numeric(AddRow))

data2 <- data2 %>% 
  mutate(id = c(1:6))
})

renderPlot({
  data2 <- data2 %>% 
    filter(indicateur == 'patient_gender') %>% 
    filter(p_n != 0) %>% 
    select(-c(p_n, indicateur))

AddRow=c(NA, 
         nrow(data2)+1, 
         data2[1,(ncol(data2)-1):ncol(data2)])
data2 <- rbind(data2, as.numeric(AddRow))

data2 <- data2 %>% 
  mutate(id = c(1:6))

ggplot(data=data2, aes(x=id)) +
  geom_polygon(aes(y=standard),color = "black", fill= "#ffd200",alpha=0.1)+
  geom_point(aes(y=standard, fill= "#ffd200"),size=5,shape=21,color = 'black',fill= "#ffd200")+
  
  geom_polygon(aes(y=mean),color = "black", fill= "#304156",alpha=0.1)+
  geom_point(aes(y=mean, fill= "#304156"),size=5,shape=21,color = 'black', fill= "#304156")+
  
  geom_polygon(aes(y=median),color = "black", fill= "#f8766d",alpha=0.1)+
  geom_point(aes(y=median, fill= "#f8766d"),size=5,shape=21,color = 'black', fill= "#f8766d")+
  
  coord_polar() +
  scale_x_continuous(breaks =data2$id,labels=data2$name)+
  theme_light()+
  theme(axis.text.x=element_text(size = 8,colour="black"))+
    labs(
    title = "Comparison of male indicators",
    subtitle = " ",
    caption = "Data source: Aymeric Stamm"  )
})
```

