---
title: "Patient group comparison"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(shiny)
library(readr)

library(ggplot2)

data1 <- read.csv("../A_Datas/thyroid_tidy.csv",encoding = 'UTF-8')
data2 <- read.csv("../A_Datas/df_tidy_for_db3.csv")
data3 <- read.csv("../A_Datas/df_tidy_for_db2.csv")


```


Sidebar {.sidebar}
=======================================================================


```{r}
type <- c("patient_gender", "presc_thyroxine", "queried_why_on_thyroxine", 
          #"presc_anthyroid_meds", 
          "sick", 
          #"pregnant", "thyroid_surgery", 
          "radioactive_iodine_therapyI131", "query_hypothyroid", "query_hyperthyroid", "lithium", "goitre", "tumor", "hypopituitarism", "psych_condition", "TSH_measured", "T3_measured", 
          # "T4_measured", 
          "thyrox_util_rate_T4U_measured", "FTI_measured")

selectInput('xcol', 'X Variable', 
            list(
              "The reading result of the Free triiodothyronine" = "T3_reading_fill",       
              "The reading result of the Free thyroxine" = "T4_reading_fill",     
              "The reading result of the TSH blood test" = "TSH_reading_fill",     
              "The result of the Free Thyroxine Index" = "FTI_reading_fill",    
              "The result of the thyroxine utilisation rate" = "T4U_rate_reading_fill"))

selectInput('ycol', 'Y Variable',             
            list(
              "The result of the Free Thyroxine Index" = "FTI_reading_fill", 
              "The reading result of the Free thyroxine" = "T4_reading_fill",  
              "The reading result of the Free triiodothyronine" = "T3_reading_fill",       
              "The reading result of the TSH blood test" = "TSH_reading_fill",     
              "The result of the thyroxine utilisation rate" = "T4U_rate_reading_fill"))

selectInput('var', 'Influencing Factors',
            list("Patient Gender" = "patient_gender",
                 "whether thyroxine replacement prescribed" = "presc_thyroxine",
                 
                 "query has been actioned" = "queried_why_on_thyroxine", 
                 "sickness due to thyroxine depletion or over activity" = "sick",
                 "whether anti-thyroid medicine has been prescribed" = "presc_anthyroid_meds",
                 "whether the patient has had thyroid surgery" = "thyroid_surgery",
                 "Pregnant or not"  = "pregnant",
                 "whether patient has had radioactive iodine treatment" = "radioactive_iodine_therapyI131", 
                 "under active thyroid query" = "query_hypothyroid", 
                 "over active thyroid query" = "query_hyperthyroid", 
                 "Lithium carbonate administered to decrease the level of thyroid hormones" = "lithium", 
                 "swelling of the thyroid gland" = "goitre", 
                 "Have a tumor" = "tumor", 
                 "a diagnosed under active thyroid" = "hypopituitarism", 
                 "whether a patient has a psychological condition" = "psych_condition", 
                 "A TSH level lower than normal" = "TSH_measured", 
                 "Is the thyroid gland hyperactive" = "T4_measured",
                 "free triiodothyronine rise above normal" = "T3_measured", 
                 "the thyroxine utilisation rate" = "thyrox_util_rate_T4U_measured", 
                 "measurement on the Free Thyroxine Index" = "FTI_measured"))
# c(colnames(data1)[2:24],colnames(data1)[30]),
                # selected=colnames(data1)[[5]])

selectInput("variable",  # 传入变量名称
            "Positive or not (Gender: F/ M)", # 提示文字
            list("Positive" = "1",
                 "Negative" = "0"))
    
# varSelectInput("variable", "Variable:", data)
```

Ⅱ.Summaries {data-orientation=rows}
=======================================================================


Column {data-width=400}
-----------------------------------------------------------------------
### Comparison of different factors
```{r}
renderPlot({
df_2 <- data3 %>% 
  filter(indicateur == input$var)

df_2$positive[df_2$positive == 0 ]<-"NO"
df_2$positive[df_2$positive == 1 ]<-"YES"

df_2 %>% 
  ggplot(aes(x = positive, y = count)) +
  geom_col(aes(colour=positive, fill=positive), position = "dodge")+
  facet_grid( ~ ThyroidClass) + labs(
    x = " ",
    # title = "Numerical variable comparison",
    subtitle = " ",
    caption = "Data source: Mr.Aymeric Stamm")
})
```

### Comparison of different age groups
```{r}
renderPlot({
df_2 <- data3 %>% 
  filter(indicateur == input$var)

df_2$positive[df_2$positive == 0 ]<-"NO"
df_2$positive[df_2$positive == 1 ]<-"YES"

df_2 %>% 
  ggplot(aes(x = patient_age_Seg, y = count)) +
  geom_col(aes(colour=positive , fill=positive ), position = "dodge")+
  facet_wrap( ~ ThyroidClass,nrow=2) + labs(
    x = "age",
    # title = "Numerical variable comparison",
    subtitle = " ",
    caption = "Data source: Mr.Aymeric Stamm")
})

```

