---
title: "Based on col"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```
Sidebar {.sidebar}
=======================================================================

```{r}
# Définir la barre latérale (onglets)
```
Page 1
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```




Page 2 {data-orientation=rows}
=======================================================================

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart A.1

```{r}

```

### Chart A.2

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```
