---
title: "Patient group comparison"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(shiny)
library(readr)

data1 <- read.csv("../A_Datas/thyroid_tidy.csv",encoding = 'UTF-8')
data2 <- read.csv("../A_Datas/df_tidy_for_db3.csv")
```


Input {.sidebar}
-----------------------------------------------------------


```{r}
type <- c("patient_gender", "presc_thyroxine", "queried_why_on_thyroxine", 
          #"presc_anthyroid_meds", 
          "sick", 
          #"pregnant", "thyroid_surgery", 
          "radioactive_iodine_therapyI131", "query_hypothyroid", "query_hyperthyroid", "lithium", "goitre", "tumor", "hypopituitarism", "psych_condition", "TSH_measured", "T3_measured", 
          # "T4_measured", 
          "thyrox_util_rate_T4U_measured", "FTI_measured")

selectInput('xcol', 'X Variable', colnames(data1)[25:29],
                selected=colnames(data1)[[25]])

selectInput('ycol', 'Y Variable', colnames(data1)[25:29],
                selected=colnames(data1)[[26]])

selectInput('var', 'Variable', c(colnames(data1)[2:24],colnames(data1)[30]),
                selected=colnames(data1)[[5]])

p("=============================")
p("Patient group comparison")
p("=============================")
selectInput('data', 'Different patient groups', 
            list("whether thyroxine replacement prescribed" = "presc_thyroxine",
                 "Patient Gender" = "patient_gender",
                 "query has been actioned" = "queried_why_on_thyroxine", 
                 "sickness due to thyroxine depletion or over activity" = "sick", 
                 "whether patient has had radioactive iodine treatment" = "radioactive_iodine_therapyI131", 
                 "under active thyroid query" = "query_hypothyroid", 
                 "over active thyroid query" = "query_hyperthyroid", 
                 "Lithium carbonate administered to decrease the level of thyroid hormones" = "lithium", 
                 "swelling of the thyroid gland" = "goitre", 
                 "Have a tumor" = "tumor", 
                 "a diagnosed under active thyroid" = "hypopituitarism", 
                 "whether a patient has a psychological condition" = "psych_condition", 
                 "A TSH level lower than normal" = "TSH_measured", 
                 "free triiodothyronine rise above normal" = "T3_measured", 
                 "the thyroxine utilisation rate" = "thyrox_util_rate_T4U_measured", 
                 "measurement on the Free Thyroxine Index" = "FTI_measured"))

selectInput("variable",  # 传入变量名称
            "Yes or No (Gender: F/ M)", # 提示文字
            list("Yes" = "1",
                 "No" = "0"))
    
# varSelectInput("variable", "Variable:", data)
```

Column {data-width=600}
-----------------------------------------------------------------------

### Numerical variable comparison

```{r, fig.height=10}
data1_2 <- data1 %>% 
  filter(ThyroidClass == "sick")

renderPlot({
  ggplot(data = data1_2, 
         mapping = aes_string(x = input$xcol,
                       y = input$ycol,
                       color = input$var)) + 
  geom_point() +
    labs(
    x = as.character(input$xcol),
    y = as.character(input$ycol),
    # title = "Numerical variable comparison",
    subtitle = " ",
    caption = "Data source: Aymeric Stamm"  )
})
```

### Indicator board
```{r}
renderText({
  if ((input$data == 'presc_thyroxine') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Prescribed thyroxine replacement! ')}
  else if((input$data == 'presc_thyroxine') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Thyroxine replacement not prescribed! ')}
  
  else if((input$data == 'patient_gender') & (input$variable==1))
  {print('ฅ՞•ﻌ•՞ฅ Female patient group presentation! ')}
  else if((input$data == 'patient_gender') & (input$variable==0))
  {print('◔.̮◔✧ Male patient group presentation! ')}
  
  else if((input$data == 'queried_why_on_thyroxine') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Queried Executed Operations! ')}
  else if((input$data == 'queried_why_on_thyroxine') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Not Querying Executed Operations! ')}
  
  else if((input$data == 'sick') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Have a disease caused by thyroxine depletion or over-activity! ')}
  else if((input$data == 'sick') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ No illness due to thyroxine depletion or over activity! ')}
  
  else if((input$data == 'radioactive_iodine_therapyI131') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patient has received radioactive iodine treatment! ')}
  else if((input$data == 'radioactive_iodine_therapyI131') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Patient has not been treated with radioactive iodine! ')}
  
  else if((input$data == 'lithium') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patients are given lithium carbonate to lower thyroid hormone levels! ')}
  else if((input$data == 'lithium') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Patient not given lithium carbonate to lower thyroid hormone levels! ')}
  
  else if((input$data == 'goitre') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Swelling of the thyroid gland! ')}
  else if((input$data == 'goitre') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ No swelling of the thyroid gland! ')}
  
  else if((input$data == 'tumor') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patient has a tumor! ')}
  else if((input$data == 'tumor') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Patient does not have a tumor! ')}
  
  else if((input$data == 'hypopituitarism') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patient diagnosed under thyroid activity! ')}
  else if((input$data == 'hypopituitarism') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Patients are not diagnosed under thyroid activity! ')}
  
  else if((input$data == 'psych_condition') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patients with psychological conditions! ')}
  else if((input$data == 'psych_condition') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ The patient has no psychological condition! ')}
  
  else if((input$data == 'TSH_measured') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patient with hyperthyroidism! ')}
  else if((input$data == 'TSH_measured') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Patient does not have hyperthyroidism! ')}
  
  else if((input$data == 'T3_measured') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patient with hyperthyroidism! ')}
  else if((input$data == 'T3_measured') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Patient does not have hyperthyroidism! ')}
  
  else if((input$data == 'thyrox_util_rate_T4U_measured') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patient with hyperthyroidism! ')}
  else if((input$data == 'thyrox_util_rate_T4U_measured') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Patient does not have hyperthyroidism! ')}
  
  else if((input$data == 'FTI_measured') & (input$variable==1))
    {print(',,Ծ‸Ծ,, Patient with hyperthyroidism! ')}
  else if((input$data == 'FTI_measured') & (input$variable==0))
  {print('ฅ՞•ﻌ•՞ฅ Patient does not have hyperthyroidism! ')}
  })
```
Column {data-width=500}
-----------------------------------------------------------------------

### Comparison group data table
```{r}
renderTable({
data2 %>% 
    filter(p_n == input$variable, indicateur == input$data) %>% 
    select(-c(p_n, indicateur))
})
```

### Comparison of indicators in different patient groups
```{r}
renderPlot({
  data2 <- data2 %>% 
    filter(p_n == input$variable, indicateur == input$data) %>% 
    select(-c(p_n, indicateur))

AddRow=c(NA, 
         nrow(data2)+1, 
         data2[1,(ncol(data2)-1):ncol(data2)])
data2 <- rbind(data2, as.numeric(AddRow))

data2 <- data2 %>% 
  mutate(id = c(1:6))
data2  %>%
  ggplot(aes(x=id)) +
  geom_polygon(aes(y=standard),color = "black", fill= "#ffd200",alpha=0.1)+
  geom_point(aes(y=standard, fill= "#ffd200"),size=5,shape=21,color = 'black',fill= "#ffd200")+
  
  geom_polygon(aes(y=mean),color = "black", fill= "#304156",alpha=0.1)+
  geom_point(aes(y=mean, fill= "#304156"),size=5,shape=21,color = 'black', fill= "#304156")+
  
  geom_polygon(aes(y=median),color = "black", fill= "#f8766d",alpha=0.1)+
  geom_point(aes(y=median, fill= "#f8766d"),size=5,shape=21,color = 'black', fill= "#f8766d")+
  
  coord_polar() +
  scale_x_continuous(breaks =data2$id,labels=data2$name)+
  theme_light()+
  theme(axis.text.x=element_text(size = 7.2,colour="black"))+
    labs(
    # title = " ",
    subtitle = "Tips: Red: Mediam, Yellow: Standard, Gray: Mean",
    caption = "Data source: Aymeric Stamm"  )
})
```


