---
title: "Vis"
author: "ZG"
date: "2022-12-25"
output: html_document
---
```{r setup}
library(tidyverse)
library(skimr)
library(readr)

library(ggplot2)
library(patchwork)
```

# 1.Importation des données
```{r}
data1 <- read.csv("../A_Datas/thyroid_tidy.csv",encoding = 'UTF-8')
# thyroid <- read_csv("C:/Users/roman/Downloads/thyroid.csv")
problems(data1)

# Résoudre le problème de jeu des données
data1$patient_age[which(data1$patient_age =='28;0')] <- 28
data1$FTI_measured[which(data1$FTI_measured ==119)] <- 1

# Afficher les données
skim(data1)
```
# Visualisation des données

```{r}
ggplot() + geom_bar(data = data1, aes(x = patient_age, fill = ThryroidClass), stat = "count",position = "dodge")+ scale_fill_brewer(palette = 'Accent')

ggplot() + geom_bar(data = data1, aes(x = patient_gender, fill = ThryroidClass), stat = "count",position = "dodge")
```

```{r}
set.seed(13)
data <- data.frame(num = rep(c(seq(from = 10, to = 100, by = 10),
 rev(seq(from = 40, to = 90, by = 10))), 
 times = 2),
 age = rep(seq(from = 80, to = 5, by = -5), 
 times = 2),
 gender = rep(c("male", "female"), each = 16))

# 根据性别对num赋值
data$num2 <- ifelse(data$gender == "male", 
 data$num *1,
 data$num * -1)

ggplot(data = data) + geom_col(aes(x = factor(age), 
 y = num2, 
 fill = gender)) + 
 scale_y_continuous(breaks = seq(from = -100, to = 100,
 by = 20),
 labels = c(seq(100, 0, -20), 
 seq(20, 100, 20))) + 
 coord_flip() + theme_bw()
```



```{r}
plot_normal <- data1 %>% 
  filter(sick == 0) %>% 
  ggplot(mapping = aes(x = patient_age)) + 
  geom_freqpoly()
plot_sick <- data1 %>% 
  filter(sick == 1) %>% 
  ggplot(mapping = aes(x = patient_age)) + 
  geom_freqpoly()

# Mapping
plot_normal + plot_sick + plot_layout(nrow = 3)
```
```{r}
data1 %>% 
  filter(sick == 1) %>% 
  ggplot(mapping = aes(x = FTI_reading_fill)) + 
  geom_freqpoly(mapping = aes(colour = patient_age_Seg))
```

