---
title: "Vis"
author: "ZG"
date: "2022-12-25"
output: html_document
---
```{r setup}
library(tidyverse)
library(skimr)
library(readr)

library(ggplot2)
library(patchwork)
library(plotly)

library(ggradar)
```

# 1.Importation des données
```{r}
data1 <- read.csv("../../A_Datas/thyroid_tidy.csv",encoding = 'UTF-8')
```

```{r}
head(data1)
```


```{r}
data_sick <- data1 %>% 
  filter(ThyroidClass == "sick") %>% 
  select(-c(X, sick))

data_T3_reading_fill <- data_sick %>% 
  group_by(patient_gender) %>% 
  summarise(count = n(),
            mean = mean(T3_reading_fill), 
            median = median(T3_reading_fill))


data_T4_reading_fill <- data_sick %>% 
  group_by(patient_gender) %>% 
  summarise(count = n(),
            mean = mean(T4_reading_fill), 
            median = median(T4_reading_fill))

data_TSH_reading_fill <- data_sick %>% 
  group_by(patient_gender) %>% 
  summarise(count = n(),
            mean = mean(TSH_reading_fill), 
            median = median(TSH_reading_fill))
  
data_FTI_reading_fill <- data_sick %>% 
  group_by(patient_gender) %>% 
  summarise(count = n(),
            mean = mean(FTI_reading_fill), 
            median = median(FTI_reading_fill))
  
data_T4U_rate_reading_fill <- data_sick %>% 
  group_by(patient_gender) %>% 
  summarise(count = n(),
            mean = mean(T4U_rate_reading_fill), 
            median = median(T4U_rate_reading_fill))
  
```


```{r}
z <- rbind(data_T3_reading_fill,
           data_T4_reading_fill,
           data_TSH_reading_fill,
           data_FTI_reading_fill, 
           data_T4U_rate_reading_fill)
z <- filter(z, patient_gender==0)
name <- c("T3_reading",
        "T4_reading",
        "TSH_reading",
        "FTI_reading",
        "T4U_rate_reading")

z <- cbind(name, z) %>% 
  select(-(patient_gender))
```

```{r}
z %>% write.csv(file = "../../A_Datas/age.csv", row.names=F)


z_t <- t(z)

colnames(z_t)<-z_t[1,]
z_t <- z_t[-1,]

indicateur <- rownames(z_t)
z_t <- cbind(indicateur, z_t)
rownames(z_t) <- 1:nrow(z_t)

z_t %>% write.csv(file = "../../A_Datas/age_2.csv")
```


```{r}
data3 <- read.csv("../../A_Datas/age_2.csv",encoding = 'UTF-8')
skim(data3)
```
```{r}
data3 %>% 
  ggplot(aes(T3_reading, T4_reading)) + 
  geom_point()
```

```{r}
ggplot(data=data3,aes(x=indicateur, y=T3_reading)) +
  geom_polygon(color = "black", fill= "#E41A1C",alpha=0.1)+
  geom_point(size=3,shape=21,color = 'black', fill= "#E41A1C")+
  coord_polar() +
  theme_light()+
  theme(axis.text.x=element_text(size = 11,colour="black"))
```

```{r}
ggplot(data=data2,aes(x=id)) +
  geom_polygon(aes(y=student1),color = "black", fill= "#ffd200",alpha=0.1)+
  geom_point(aes(y=student1, fill= "#ffd200"),size=5,shape=21,color = 'black',fill= "#ffd200")+
  geom_polygon(aes(y=student2),color = "black", fill= "#304156",alpha=0.1)+
  geom_point(aes(y=student2, fill= "#304156"),size=5,shape=21,color = 'black', fill= "#304156")+
  geom_polygon(aes(y=student3),color = "black", fill= "#f8766d",alpha=0.1)+
  geom_point(aes(y=student3, fill= "#f8766d"),size=5,shape=21,color = 'black', fill= "#f8766d")+
  coord_polar() +
  scale_x_continuous(breaks =course_data2$id,labels=course_data2$course)+
  ylim(50,100)+
  theme_light()+
  theme(axis.text.x=element_text(size = 11,colour="black"))+
  xlab("")+ylab("")
```


```{r}

#雷达图3
ggradar(data2,
        base.size = 20,
        values.radar = c("0", "50", "100"),
        grid.min = 0, grid.mid = 60, grid.max = 120,
        group.line.width = 1,
        group.point.size = 3,
        background.circle.colour = "white",
        gridline.mid.colour = "grey",
        
        legend.title = "Indicators",
        legend.text.size = 10,
        plot.title = "A")

```



```{r}
z_t <- t(z)
colnames(z_t)<-z_t[1,]

z_t <- z_t[-1,]
as.numeric(z_t$T3_reading)
as.numeric(z_t$T4_reading)
as.numeric(z_t$TSH_reading)
as.numeric(z_t$FTI_reading)
as.numeric(z_t$T4U_rate_reading)
```



# [old]Visualisation des données

```{r}
ggplot() + geom_bar(data = data1, aes(x = patient_age, fill = ThryroidClass), stat = "count",position = "dodge")+ scale_fill_brewer(palette = 'Accent')

ggplot() + geom_bar(data = data1, aes(x = patient_gender, fill = ThryroidClass), stat = "count",position = "dodge")
```
```{r}
data_gender_sick <- data1 %>% 
  group_by(patient_gender, sick) %>% 
  summarise(n = n(), .groups = "drop_last")

df <- t(data_gender_sick)
colnames(df) <- c("m_nor", "m_sick", "fe_nor", "fe_sick")
df_v1 <- df[-c(1:2),]
head(df_v1)

x <- c('male', 'female')
y <- c(1241, 31)
y2 <- c(2384,96)
data <- data.frame(x, y, y2)

# Visualisation
fig <- data %>% plot_ly()
fig <- fig %>% add_trace(x = ~x, y = ~y, type = 'bar',
             textposition = 'auto',
             name = 'male',
             marker = list(color = 'rgb(158,202,225)',
                           line = list(color = 'rgb(8,48,107)', width = 1.5)))

fig <- fig %>% add_trace(x = ~x, y = ~y2, type = 'bar',
            textposition = 'auto',
            name = 'female',
            marker = list(color = 'rgb(58,200,225)',
                          line = list(color = 'rgb(8,48,107)', width = 1.5)))

fig <- fig %>% layout(title = "Taux de maladie pour les hommes et les femmes",
         barmode = 'group',
         xaxis = list(title = ""),
         yaxis = list(title = ""))

fig
```



```{r}
set.seed(13)
data <- data.frame(num = rep(c(seq(from = 10, to = 100, by = 10),
 rev(seq(from = 40, to = 90, by = 10))), 
 times = 2),
 age = rep(seq(from = 80, to = 5, by = -5), 
 times = 2),
 gender = rep(c("male", "female"), each = 16))

# 根据性别对num赋值
data$num2 <- ifelse(data$gender == "male", 
 data$num *1,
 data$num * -1)

ggplot(data = data) + geom_col(aes(x = factor(age), 
 y = num2, 
 fill = gender)) + 
 scale_y_continuous(breaks = seq(from = -100, to = 100,
 by = 20),
 labels = c(seq(100, 0, -20), 
 seq(20, 100, 20))) + 
 coord_flip() + theme_bw()
```



```{r}
plot_normal <- data1 %>% 
  filter(sick == 0) %>% 
  ggplot(mapping = aes(x = patient_age)) + 
  geom_freqpoly()
plot_sick <- data1 %>% 
  filter(sick == 1) %>% 
  ggplot(mapping = aes(x = patient_age)) + 
  geom_freqpoly()

# Mapping
plot_normal + plot_sick + plot_layout(nrow = 3)
```
```{r}
data1 %>% 
  filter(sick == 1) %>% 
  ggplot(mapping = aes(x = FTI_reading_fill)) + 
  geom_freqpoly(mapping = aes(colour = patient_age_Seg))
```

